language: php
dist: trusty

php:
  - '7.2'
  - '7.3'

matrix:
  include:
    - php: '7.2'
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction

script:
  - vendor/bin/phpstan --level=max analyse src
  - vendor/bin/phpcs --standard=PSR2 src
